/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class VEmpHome extends javax.swing.JFrame {

    /**
     * Creates new form VEmpHome
     */
    public VEmpHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewSalary = new javax.swing.JButton();
        btnApplyLeave = new javax.swing.JButton();
        btnComplaints = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewSalary.setBackground(new java.awt.Color(255, 255, 255));
        btnViewSalary.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        btnViewSalary.setText("View Salary");
        btnViewSalary.setPreferredSize(new java.awt.Dimension(200, 45));
        btnViewSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSalaryActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        btnApplyLeave.setBackground(new java.awt.Color(255, 255, 255));
        btnApplyLeave.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        btnApplyLeave.setText("Apply for Leave");
        btnApplyLeave.setPreferredSize(new java.awt.Dimension(200, 45));
        btnApplyLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyLeaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnApplyLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 54, -1, -1));

        btnComplaints.setBackground(new java.awt.Color(255, 255, 255));
        btnComplaints.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        btnComplaints.setText("Log Complaints");
        btnComplaints.setPreferredSize(new java.awt.Dimension(200, 45));
        btnComplaints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplaintsActionPerformed(evt);
            }
        });
        getContentPane().add(btnComplaints, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 54, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 50, 64, 50));

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setPreferredSize(new java.awt.Dimension(200, 45));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 54, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bgE.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1400, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        int r=JOptionPane.showConfirmDialog(null,"Do you really want to close the Application?","Select",JOptionPane.YES_NO_OPTION);
       if(r==0)
       {
           System.exit(0);
       }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnApplyLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyLeaveActionPerformed
        new VELeaveApplication().setVisible(true);
    }//GEN-LAST:event_btnApplyLeaveActionPerformed

    private void btnComplaintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplaintsActionPerformed
     new VComplaints1().setVisible(true);
    }//GEN-LAST:event_btnComplaintsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        setVisible(false);
         new VLogin().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnViewSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSalaryActionPerformed
        new VEViewSalary().setVisible(true);
    }//GEN-LAST:event_btnViewSalaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEmpHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEmpHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEmpHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEmpHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VEmpHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyLeave;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnComplaints;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnViewSalary;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
