/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CGenerateSalary;
import Model.MSelect;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author user
 */
public class VGenerateSalary extends javax.swing.JFrame {

    /**
     * Creates new form VGenerateSalary
     */
    public VGenerateSalary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtemail = new javax.swing.JTextField();
        txtBsalary = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFinalSalary = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        txtetf = new javax.swing.JTextField();
        txtEpf = new javax.swing.JTextField();
        txtOther = new javax.swing.JTextField();
        txtAllowances = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dtp1 = new com.toedter.calendar.JDateChooser();
        txtId = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(335, 150));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(975, 550));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Generate  Salary");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 27, 307, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel2.setText("Emp Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 103, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 173, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel4.setText("Basic Salary");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel5.setText("Allowances");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        btnGenerate.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        btnGenerate.setForeground(new java.awt.Color(153, 153, 0));
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, -1));

        btnClear.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        btnClear.setForeground(new java.awt.Color(153, 153, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel6.setText("ETF");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel7.setText("EPF");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel8.setText("Deductions");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel9.setText("Other");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));

        btnSearch.setBackground(new java.awt.Color(255, 0, 0));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.setPreferredSize(new java.awt.Dimension(100, 30));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 101, -1, -1));

        txtemail.setFocusable(false);
        txtemail.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 173, 198, -1));

        txtBsalary.setFocusable(false);
        txtBsalary.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txtBsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel10.setText("Final Salary");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        txtFinalSalary.setBackground(new java.awt.Color(255, 0, 0));
        txtFinalSalary.setForeground(new java.awt.Color(255, 255, 255));
        txtFinalSalary.setFocusable(false);
        txtFinalSalary.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txtFinalSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 21, 50, 40));

        txtetf.setFocusable(false);
        txtetf.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txtetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        txtEpf.setFocusable(false);
        txtEpf.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txtEpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, -1));

        txtOther.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txtOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        txtAllowances.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txtAllowances, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel11.setText("Date Issue");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        dtp1.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(dtp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 210, -1));

        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 200, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       int id=Integer.parseInt(txtId.getSelectedItem().toString());
      
        CGenerateSalary gsc= new CGenerateSalary();
       
        
       
        try{
            ResultSet rst=gsc.getData(id);
            
            while(rst.next())
            {  
                
                txtemail.setText(rst.getString(1));
                 txtBsalary.setText(String.valueOf(rst.getDouble(2)));
            }
           
          String value=txtBsalary.getText();
            double bs=Double.parseDouble(value);
             double epf=(bs*8/100)+(bs*12/100);
           double etf=bs*2/100;
           txtEpf.setText(Double.toString(epf));
             txtetf.setText(Double.toString(etf)); 
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        
        int eid=Integer.parseInt(txtId.getSelectedItem().toString());
        double bs=Double.parseDouble(txtBsalary.getText());
        double epf=Double.parseDouble(txtEpf.getText());
        double etf=Double.parseDouble(txtetf.getText());
        double allowances=Double.parseDouble(txtAllowances.getText());
        double other=Double.parseDouble(txtOther.getText());
        double fr=bs+allowances-etf-other;
        txtFinalSalary.setText(Double.toString(fr));
        double fs=Double.parseDouble(txtFinalSalary.getText());
        Date dob;
        String mydob="";
        try
        {
             dob=dtp1.getDate();
            DateFormat format1=new SimpleDateFormat("yyyy-MM-dd");
          mydob=format1.format(dob);
       
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
        
        CGenerateSalary gsc=new CGenerateSalary();
      gsc.setData(bs,mydob,allowances,etf,epf,other,fs,eid);
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       setVisible(false);
       new VGenerateSalary().setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        ResultSet rs=MSelect.getData("select * from tblEmployee" );
      
        try
      {
          while(rs.next())
          {
              txtId.addItem(String.valueOf(rs.getInt(1)));
          }
           rs.close();
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null, e.getMessage());
      }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VGenerateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VGenerateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VGenerateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VGenerateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VGenerateSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnSearch;
    private com.toedter.calendar.JDateChooser dtp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAllowances;
    private javax.swing.JTextField txtBsalary;
    private javax.swing.JTextField txtEpf;
    private javax.swing.JTextField txtFinalSalary;
    private javax.swing.JComboBox<String> txtId;
    private javax.swing.JTextField txtOther;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtetf;
    // End of variables declaration//GEN-END:variables
}
