/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.MInsertUpdateDelete;
import Model.MSelect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class VLeaveDetails extends javax.swing.JFrame {

    /**
     * Creates new form VComplaints
     */
    public VLeaveDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnLeaveReport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLeave = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLeave1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(335, 150));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe Print", 3, 20)); // NOI18N
        jButton1.setText("Approval of Leave Applications");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLeaveReport.setBackground(new java.awt.Color(102, 102, 0));
        btnLeaveReport.setFont(new java.awt.Font("Segoe Print", 3, 20)); // NOI18N
        btnLeaveReport.setText("View Leave Report");
        btnLeaveReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveReportActionPerformed(evt);
            }
        });

        tblLeave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Leave Id", "Emp Id", "Start of leave", "End of leave", "Reason", "Approval"
            }
        ));
        tblLeave.setColumnSelectionAllowed(true);
        tblLeave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLeaveMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLeave);
        tblLeave.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblLeave.getColumnModel().getColumnCount() > 0) {
            tblLeave.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblLeave.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblLeave.getColumnModel().getColumn(2).setPreferredWidth(45);
            tblLeave.getColumnModel().getColumn(3).setPreferredWidth(45);
            tblLeave.getColumnModel().getColumn(4).setPreferredWidth(120);
            tblLeave.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        tblLeave1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Leave Id", "Emp Id", "Start of leave", "End of leave", "Reason", "Approval"
            }
        ));
        jScrollPane2.setViewportView(tblLeave1);
        tblLeave1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblLeave1.getColumnModel().getColumnCount() > 0) {
            tblLeave1.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblLeave1.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblLeave1.getColumnModel().getColumn(2).setPreferredWidth(45);
            tblLeave1.getColumnModel().getColumn(3).setPreferredWidth(45);
            tblLeave1.getColumnModel().getColumn(4).setPreferredWidth(120);
            tblLeave1.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton1)
                .addGap(59, 59, 59)
                .addComponent(btnLeaveReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btnLeaveReport)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        ResultSet rs=MSelect.getData("select * from tblLeave");
      DefaultTableModel table=(DefaultTableModel)tblLeave.getModel();
      table.setRowCount(0);
      try
      {
          while(rs.next())
          {
              table.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
          }
          rs.close();
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null, e.getMessage());
      }
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLeaveReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveReportActionPerformed
        try
        { Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/EmployeeDB","root","");
            JasperDesign design=JRXmlLoader.load("C:\\Users\\user\\Desktop\\EAD\\EmployeeManagement\\src\\View\\LeaveReport.jrxml");
            JRDesignQuery designquery=new JRDesignQuery();
            String myquery="Select * from tblLeave";
            designquery.setText(myquery);
            design.setQuery(designquery);
            
            JasperReport report=JasperCompileManager.compileReport(design);
            JasperPrint print=JasperFillManager.fillReport(report,null,con);
            
            JasperViewer.viewReport(print);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
                      
    }//GEN-LAST:event_btnLeaveReportActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tblLeaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLeaveMouseClicked
       int index=tblLeave.getSelectedRow();
        TableModel model=tblLeave.getModel();
        String id =model.getValueAt(index,0).toString();
           String appr=model.getValueAt(index,5).toString();
           int lid=Integer.parseInt(id);
           if(appr.equals("Approved"))
           {
               appr="Not Approved";
           }
           else
           {
               appr="Approved";
           }
           try
           {
           int a=JOptionPane.showConfirmDialog(null,"Do you want to change the Approval of Leave ID '"+lid+"'","Select",JOptionPane.YES_NO_OPTION);
           if(a==0)
           {
               MInsertUpdateDelete.setData("Update tblLeave set approval='"+appr+"' where leaveid='"+lid+"'","Approval changed succesfully");
               setVisible(false);
               new VLeaveDetails().setVisible(true);
           }
           }
           catch(Exception e)
           {
             JOptionPane.showMessageDialog(null,e.getMessage());
           }
    }//GEN-LAST:event_tblLeaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLeaveDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLeaveDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLeaveDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLeaveDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VLeaveDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLeaveReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblLeave;
    private javax.swing.JTable tblLeave1;
    // End of variables declaration//GEN-END:variables
}
