
package View;

import Controller.CSignUp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


public class VSignUp extends javax.swing.JFrame {

    
    public VSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSignup = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dtp1 = new com.toedter.calendar.JDateChooser();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rdbMale = new javax.swing.JRadioButton();
        rdbFemale = new javax.swing.JRadioButton();
        txtadrs1 = new javax.swing.JTextField();
        txtadrs2 = new javax.swing.JTextField();
        txtpwd = new javax.swing.JPasswordField();
        txtCpwd = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        cmbqualification = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1111.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cr3.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 50, 50));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("Sign Up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 180, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Date of Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Address 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Address 2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        btnSignup.setBackground(new java.awt.Color(0, 255, 51));
        btnSignup.setFont(new java.awt.Font("Segoe Script", 2, 12)); // NOI18N
        btnSignup.setText("Sign Up");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, -1));

        btnLogin.setBackground(new java.awt.Color(102, 255, 0));
        btnLogin.setFont(new java.awt.Font("Segoe Script", 2, 12)); // NOI18N
        btnLogin.setText("Login In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Confirm Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));
        getContentPane().add(dtp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 270, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 260, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 260, -1));

        buttonGroup1.add(rdbMale);
        rdbMale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdbMale.setText("Male");
        getContentPane().add(rdbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));

        buttonGroup1.add(rdbFemale);
        rdbFemale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdbFemale.setText("Female");
        getContentPane().add(rdbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, -1, -1));

        txtadrs1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtadrs1.setText("eg.Street");
        getContentPane().add(txtadrs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 270, -1));

        txtadrs2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtadrs2.setText("eg.City");
        getContentPane().add(txtadrs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 270, -1));

        txtpwd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 270, -1));

        txtCpwd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtCpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 270, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        cmbqualification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O/L Level", "A/L Level", "Diploma", "HND", "Masters", "Others" }));
        getContentPane().add(cmbqualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 270, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Highest Qualification");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        jLabel13.setPreferredSize(new java.awt.Dimension(769, 550));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, 550));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bgSign.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setPreferredSize(new java.awt.Dimension(768, 550));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 700, 550));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bgLog.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -40, 1650, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        String name=txtName.getText();
        String email=txtEmail.getText();
        String gender="";
        Date dob;
        String pwd=txtpwd.getText();
        String cpwd=txtCpwd.getText();
        String adrs1=txtadrs1.getText();
        String adrs2=txtadrs2.getText();
        String mydob="";
        String adrs=adrs1+","+adrs2;
        String qualification=cmbqualification.getSelectedItem().toString();
       if(rdbFemale.isSelected())
       { gender="Female";
       }
       else if(rdbMale.isSelected())
       { gender="Male";
       }
       
       try{
           dob=dtp1.getDate();
        DateFormat format1=new SimpleDateFormat("yyyy-MM-dd");
        mydob=format1.format(dob);
       
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e.getMessage());
       }
       if(name.equals("")||email.equals("")||gender.equals("")|| mydob.equals("")||pwd.equals("")||cpwd.equals("")||adrs1.equals("eg.Street")||adrs2.equals("eg.City")||adrs1.equals("")||adrs2.equals(""))
       {
           JOptionPane.showMessageDialog(null,"All the fields should be filled");
       }
       
       else if(!(pwd.equals(cpwd)))
        {
            JOptionPane.showMessageDialog(null,"Password and confim password does not match");
        }
       else
       { 
           CSignUp csc =new CSignUp();
           csc.createEmp(name,email,gender,pwd,adrs,mydob,qualification);
       }
       
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       int r=JOptionPane.showConfirmDialog(null,"Do you really want to close the Application","Select",JOptionPane.YES_NO_OPTION);
       if(r==0)
       {
           System.exit(0);
       }
       
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
      
        setVisible(false);
        new VLogin().setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> cmbqualification;
    private com.toedter.calendar.JDateChooser dtp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdbFemale;
    private javax.swing.JRadioButton rdbMale;
    private javax.swing.JPasswordField txtCpwd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtadrs1;
    private javax.swing.JTextField txtadrs2;
    private javax.swing.JPasswordField txtpwd;
    // End of variables declaration//GEN-END:variables
}
